create extension if not exists pgcrypto;

create table if not exists students (id uuid primary key default gen_random_uuid(), internal_id bigint generated always as identity unique, permanent_matricule text unique not null, last_name text not null, first_name text not null, birth_date date, gender text check (gender in ('M','F')), nationality text, father_name text, mother_name text, parent_phones text[], address text, photo_path text, previous_school text, status text not null default 'Actif', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists school_years (id uuid primary key default gen_random_uuid(), label text unique not null, is_active boolean not null default false, created_at timestamptz not null default now());
create table if not exists classes (id uuid primary key default gen_random_uuid(), name text not null, level text not null, series text, division text, school_year_id uuid references school_years(id) on delete restrict, created_at timestamptz not null default now());
create table if not exists enrollments (id uuid primary key default gen_random_uuid(), student_id uuid not null references students(id) on delete restrict, school_year_id uuid not null references school_years(id) on delete restrict, class_id uuid not null references classes(id) on delete restrict, annual_registration_number text not null unique, enrolled_at date not null default current_date, status text not null default 'Active', created_at timestamptz not null default now(), unique(student_id, school_year_id));
create table if not exists subjects (id uuid primary key default gen_random_uuid(), name text not null, code text, is_active boolean not null default true);
create table if not exists class_subjects (id uuid primary key default gen_random_uuid(), class_id uuid not null references classes(id) on delete cascade, subject_id uuid not null references subjects(id) on delete cascade, coefficient numeric(6,2) not null default 1, unique(class_id, subject_id));
create table if not exists evaluations (id uuid primary key default gen_random_uuid(), name text not null, order_index integer not null default 0, is_active boolean not null default true);
create table if not exists grades (id uuid primary key default gen_random_uuid(), enrollment_id uuid not null references enrollments(id) on delete restrict, subject_id uuid not null references subjects(id) on delete restrict, evaluation_id uuid not null references evaluations(id) on delete restrict, trimester smallint not null check (trimester between 1 and 3), value numeric(5,2), workflow_status text not null default 'Brouillon', locked_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(enrollment_id, subject_id, evaluation_id, trimester));
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid, action text not null, entity_type text not null, entity_id uuid, old_value jsonb, new_value jsonb, reason text, created_at timestamptz not null default now());
